name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: send_email1
      id: send_email1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: send_email1
        setup-command: npm install
        command: npm run test1
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SEND_EMAIL1_RESULTS: "${{steps.send_email1.outputs.result}}"
      with:
        runners: send_email1
